//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Tickets
    {
        public int id_historial { get; set; }
        public Nullable<int> id_ticket { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public string prioridad { get; set; }
        public string categoria { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<int> id_tecnico { get; set; }
    }
}
