//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Soporte_V5Entities1 : DbContext
    {
        public Soporte_V5Entities1()
            : base("name=Soporte_V5Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Historial_Tickets> Historial_Tickets { get; set; }
        public virtual DbSet<Soporte_Adjuntos> Soporte_Adjuntos { get; set; }
        public virtual DbSet<Soporte_Especialidades> Soporte_Especialidades { get; set; }
        public virtual DbSet<Soporte_Roles> Soporte_Roles { get; set; }
        public virtual DbSet<Soporte_Tickets> Soporte_Tickets { get; set; }
        public virtual DbSet<Soporte_Usuarios> Soporte_Usuarios { get; set; }
        public virtual DbSet<Soporte_EspecialidadesTecnicos> Soporte_EspecialidadesTecnicos { get; set; }
    }
}
