//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soporte_Usuarios()
        {
            this.Soporte_Tickets = new HashSet<Soporte_Tickets>();
            this.Soporte_EspecialidadesTecnicos = new HashSet<Soporte_EspecialidadesTecnicos>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public int id_rol { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Soporte_Roles Soporte_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte_Tickets> Soporte_Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte_EspecialidadesTecnicos> Soporte_EspecialidadesTecnicos { get; set; }
    }
}
