//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte_EspecialidadesTecnicos
    {
        public int id_usuario { get; set; }
        public int id_especialidad { get; set; }
        public int id_row { get; set; }
    
        public virtual Soporte_Especialidades Soporte_Especialidades { get; set; }
        public virtual Soporte_Usuarios Soporte_Usuarios { get; set; }
    }
}
