//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte_Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soporte_Tickets()
        {
            this.Soporte_Adjuntos = new HashSet<Soporte_Adjuntos>();
        }
    
        public int id_ticket { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public string prioridad { get; set; }
        public string categoria { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte_Adjuntos> Soporte_Adjuntos { get; set; }
        public virtual Soporte_Usuarios Soporte_Usuarios { get; set; }
    }
}
