//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte_Adjuntos
    {
        public int id_adjunto { get; set; }
        public int id_ticket { get; set; }
        public string nombre_archivo { get; set; }
        public string ruta_archivo { get; set; }
        public Nullable<System.DateTime> fecha_subida { get; set; }
    
        public virtual Soporte_Tickets Soporte_Tickets { get; set; }
    }
}
