//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTicketSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte_Especialidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soporte_Especialidades()
        {
            this.Soporte_EspecialidadesTecnicos = new HashSet<Soporte_EspecialidadesTecnicos>();
        }
    
        public int id_especialidad { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte_EspecialidadesTecnicos> Soporte_EspecialidadesTecnicos { get; set; }
    }
}
